services:
  postgres:
    image: postgres:15.1-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=kenv
      - POSTGRES_USER=scott

  producer:
    build:
      context: .
    restart: on-failure
    env_file:
      - ../.env
    mem_limit: 256m
    mem_reservation: 128m