name: kenv
services:
  kafka-ui:
    extends:
      file: infrastructure/compose.yml
      service: kafka-ui
    profiles:
      - default
      - infrastructure
      - producer
      - consumer
 
  zookeeper:
    extends:
      file: infrastructure/compose.yml
      service: zookeeper
    profiles:
      - default
      - infrastructure
      - producer
      - consumer

  kafka-1:
    extends:
      file: infrastructure/compose.yml
      service: kafka-1
    profiles:
      - default
      - infrastructure
      - producer
      - consumer

  kafka-2:
    extends:
      file: infrastructure/compose.yml
      service: kafka-2
    profiles:
      - default
      - infrastructure
      - producer
      - consumer

  kafka-3:
    extends:
      file: infrastructure/compose.yml
      service: kafka-3
    profiles:
      - default
      - infrastructure
      - producer
      - consumer

  kafka-init-topics:
    extends:
      file: infrastructure/compose.yml
      service: kafka-init-topics
    profiles:
      - default
      - infrastructure
      - producer
      - consumer

  postgres:
    extends:
      file: infrastructure/compose.yml
      service: postgres
    profiles:
      - default
      - infrastructure
      - producer

  producer-1:
    extends:
      file: producer/compose.yml
      service: producer
    environment:
      - PRODUCER_ID=1
    profiles:
      - default
      - producer
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully

  producer-2:
    extends:
      file: producer/compose.yml
      service: producer
    environment:
      - PRODUCER_ID=2
    profiles:
      - default
      - producer
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully

  producer-3:
    extends:
      file: producer/compose.yml
      service: producer
    environment:
      - PRODUCER_ID=3
    profiles:
      - default
      - producer
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully

  mongo:
    extends:
      file: infrastructure/compose.yml
      service: mongo
    profiles:
      - default
      - infrastructure
      - consumer
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully
  
  consumer-1:
    extends:
      file: consumer/compose.yml
      service: consumer
    environment:
      - CONSUMER_ID=1
    profiles:
      - default
      - consumer
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully

  consumer-2:
    extends:
      file: consumer/compose.yml
      service: consumer
    environment:
      - CONSUMER_ID=2
    profiles:
      - default
      - consumer
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully

  consumer-3:
    extends:
      file: consumer/compose.yml
      service: consumer
    environment:
      - CONSUMER_ID=3
    profiles:
      - default
      - consumer
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully