name: kenv
services:
  kafka-ui:
    extends:
      file: infrastructure/compose.yml
      service: kafka-ui
    profiles:
      - default
      - infrastructure
      - producers
      - consumers
 
  zookeeper:
    extends:
      file: infrastructure/compose.yml
      service: zookeeper
    profiles:
      - default
      - infrastructure
      - producers
      - consumers

  kafka-1:
    extends:
      file: infrastructure/compose.yml
      service: kafka-1
    profiles:
      - default
      - infrastructure
      - producers
      - consumers

  kafka-2:
    extends:
      file: infrastructure/compose.yml
      service: kafka-2
    profiles:
      - default
      - infrastructure
      - producers
      - consumers

  kafka-3:
    extends:
      file: infrastructure/compose.yml
      service: kafka-3
    profiles:
      - default
      - infrastructure
      - producers
      - consumers

  kafka-init-topics:
    extends:
      file: infrastructure/compose.yml
      service: kafka-init-topics
    profiles:
      - default
      - infrastructure
      - producers
      - consumers

  postgres:
    extends:
      file: producer/compose.yml
      service: postgres
    profiles:
      - default
      - infrastructure
      - producers

  producer-1:
    extends:
      file: producer/compose.yml
      service: producer
    environment:
      - PRODUCER_ID=1
    profiles:
      - default
      - producers

  producer-2:
    extends:
      file: producer/compose.yml
      service: producer
    
    environment:
      - PRODUCER_ID=2
    profiles:
      - default
      - producers

  producer-3:
    extends:
      file: producer/compose.yml
      service: producer
    environment:
      - PRODUCER_ID=3
    profiles:
      - default
      - producers

  mongo:
    extends:
      file: consumer/compose.yml
      service: mongo
    profiles:
      - default
      - infrastructure
      - consumers
  
  consumer-1:
    extends:
      file: consumer/compose.yml
      service: consumer
    environment:
      - CONSUMER_ID=1
    profiles:
      - default
      - consumers

  consumer-2:
    extends:
      file: consumer/compose.yml
      service: consumer
    environment:
      - CONSUMER_ID=2
    profiles:
      - default
      - consumers

  consumer-3:
    extends:
      file: consumer/compose.yml
      service: consumer
    environment:
      - CONSUMER_ID=3
    profiles:
      - default
      - consumers