services:
  mongo:
    image: mongo:6.0.3
    ports:
      - "27017:27017"

  consumer:
    build:
      context: .
    restart: on-failure
    env_file:
      - ../.env
    mem_limit: 256m
    mem_reservation: 128m