name: kenv
services:
  kafka-ui:
    extends:
      file: ../infrastructure/compose.yml
      service: kafka-ui
 
  zookeeper:
    extends:
      file: ../infrastructure/compose.yml
      service: zookeeper

  kafka-1:
    extends:
      file: ../infrastructure/compose.yml
      service: kafka-1

  kafka-2:
    extends:
      file: ../infrastructure/compose.yml
      service: kafka-2

  kafka-3:
    extends:
      file: ../infrastructure/compose.yml
      service: kafka-3

  kafka-init-topics:
    extends:
      file: ../infrastructure/compose.yml
      service: kafka-init-topics

  mongo:
    extends:
      file: ../infrastructure/compose.yml
      service: mongo

  consumer:
    build:
      context: .
    restart: on-failure
    env_file:
      - ../.env
    mem_limit: 256m
    mem_reservation: 128m
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully
    