spring:
  main.web-application-type: none
  kafka.consumer:
#    client-id: consumer
    auto-offset-reset: earliest
    group-id: consumer
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.type.mapping: >
          user:com.github.marceloleite2604.kafkaenvironment.consumer.domain.user.dto.UserDto,
          address:com.github.marceloleite2604.kafkaenvironment.consumer.domain.address.Address
  data.mongodb.uri: mongodb://localhost:27017/kenv

consumer.kafka.topics.users: users