spring:
  batch.jdbc.initialize-schema: always
  codec:
    max-in-memory-size: 10MB
  main.web-application-type: none
  kafka.producer:
    client-id: producer
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json:
        add.type.headers: true
        type.mapping: >
          user:com.github.marceloleite2604.kafkaenvironment.producer.domain.user.User,
          address:com.github.marceloleite2604.kafkaenvironment.producer.domain.address.Address
  datasource:
    type:
    url: jdbc:postgresql://localhost:5432/kenv
    username: scott

producer:
  job.steps:
    users-retrieval:
      total-items: 25000
      chunk-size: 50
      buffered-items: 250
      failure-chance-rate: 0.001
    addresses-retrieval:
      total-items: 100000
      chunk-size: 100
      buffered-items: 10
      failure-chance-rate: 0.001
  kafka.topics:
    users: users
    addresses: addresses

logging.level:
  root: INFO
  com.github.marceloleite2604.kafkaenvironment.producer: DEBUG